name: Website
on:
  push:
    tags: ["v*"]

jobs:
  website:
    name: Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Packages
        run: npm install
      - name: Build
        run: npm run -s docs:build
      - name: Deploy
        run: |
          cd docs/.vuepress/dist
          git init
          git config user.email "public@mysticatea.dev"
          git config user.name "Toru Nagashima"
          git add .
          git commit -m "stash"
          git remote add origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git fetch origin gh-pages
          git checkout gh-pages
          rm -rf * .nojekyll
          git checkout master -- .
          git add .
          git commit -m "Update Website"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
